version: "3.8"

services:
  test:
    build:
      context: .
      target: test
      additional_contexts:
        libiris: ./.libiris
    command: ["ctest", "--test-dir", "build", "--output-on-failure", "-V"]

